<?php
/**
 * @var \Borisperevyazko\GoogleMarkup\Block\JsonLd $block
 */
?>
<?php
/** @var \Borisperevyazko\GoogleMarkup\Api\JsonLdTypeInterface $jsonLd */
$jsonLd = $block->getJsonLd();
?>

    <script>
        require(["jquery"], function ($) {
            $.ajax({
                url: "<?php echo $block->escapeUrl($block->getAjaxUrl()); ?>",
                type: 'post',
                dataType: 'json',
                cache: false,
                data: <?php /* @noEscape */ echo $block->getPostData(); ?>,
                success: function(data) {
                },
                complete: function() {}
            });
        });
    </script>